version: '3.9'

services:

  django:
    image: forms_service_development
    container_name: forms_service_development_django
    build:
      context: ..
      dockerfile: Dockerfile
    restart: always
    env_file: ../.env/.env.development
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    volumes:
      - ..:/forms_service
    command: sh -c "chmod +x ./entrypoint.sh && sh ./entrypoint.sh"

  postgres:
    image: postgres:13-alpine
    container_name: forms_service_development_postgres
    env_file: ../.env/.env.development
    ports:
      - "5432:5432"
    volumes:
      - ../../.volumes/forms_service/postgres_data:/var/lib/postgresql/data

  postgres_test:
    image: postgres:13-alpine
    container_name: forms_service_development_postgres_test
    env_file: ../.env/.env.development
    ports:
      - "5433:5432"
    volumes:
      - ../../.volumes/forms_service/postgres_test_data:/var/lib/postgresql/data
