version: '3.9'

services:

  django:
    image: forms_service_production
    container_name: forms_service_production_django
    build:
      context: ..
      dockerfile: Dockerfile
      args:
        ENVIRONMENT: "production"
    restart: always
    env_file: ../.env/.env.production
    ports:
      - "80:8000"
    volumes:
      - ..:/forms_service
    command: sh -c "chmod +x ./entrypoint.sh && sh ./entrypoint.sh"
