apiVersion: v1
kind: Service
metadata:
  name: fuilder-forms-service
  namespace: fuilder-forms-service-namespace
  labels:
    app: fuilder-forms-service
spec:
  type: NodePort
  selector:
    app: fuilder-forms-service
  ports:
    - port: 8000
      targetPort: 8000
